os:
  - linux
  - osx
language: node_js
sudo: false
node_js:
  - "9.3"
install:
  - npm install
before_script:
  - npm install -g @angular/cli
script:
  - set -e
  - cp -r "$PWD" "../ngw"
  - cd "../"
  - ng new test-project --skip-install
  - cd test-project
  - npm i
  - cp -r "../ngw" "./node_modules/ngw"
  - ./node_modules/ngw/bin/ngw --set-up
  - npm run build
after_success:
  - npm run coverage
